%% region1

load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region1\20211108_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region1\20211109_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region1\20211110_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region1\20211111_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region1\20211112_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region1\20211113_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region1\20211115_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region1\20211116_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region1\20211117_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region1\20211118_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region1\20211119_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region1\20211122_index_new.mat');

M1region1=[M1region1day1_index_new;M1region1day2_index_new;M1region1day3_index_new;M1region1day4_index_new;M1region1day5_index_new;M1region1day6_index_new;M1region1day7_index_new;M1region1day8_index_new;M1region1day9_index_new;M1region1day10_index_new;M1region1day11_index_new;M1region1day12_index_new];
% histogram(M1region1);
% 
%% region2
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region2\20211120_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region2\20211121_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region2\20211123_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region2\20211124_index_new.mat');

M1region2=[M1region2day1_index_new;M1region2day2_index_new;M1region2day3_index_new;M1region2day4_index_new;];
% histogram(M1region2);

%% region3
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region3\20211125_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region3\20211126_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region3\20211127_index_new.mat');
M1region3=[M1region3day1_index_new;M1region3day2_index_new;M1region3day3_index_new;];
% histogram(M1region3);

%% region4
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region4\20211129_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region4\20211201_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region4\20211202_index_new.mat');
M1region4=[M1region4day1_index_new;M1region4day2_index_new;M1region4day3_index_new;];
% histogram(M1region4);
%% region5
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region5\20211203_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region5\20211204_index_new.mat');
M1region5=[M1region5day1_index_new;M1region5day2_index_new;];
% histogram(M1region5);
%% region6

load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region6\20211217_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region6\20211218_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region6\20211219_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region6\20211220_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region6\20211221_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region6\20211222_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region6\20211223_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region6\20211224_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region6\20211225_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region6\20211226_index_new.mat');

M1region6=[M1region6day1_index_new;M1region6day2_index_new;M1region6day3_index_new;M1region6day4_index_new;M1region6day5_index_new;M1region6day6_index_new;M1region6day7_index_new;M1region6day8_index_new;M1region6day9_index_new;M1region6day10_index_new;];
% histogram(M1region6);
%% region7
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region7\20220115_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region7\20220116_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M1region7\20220117_index_new.mat');
M1region7=[M1region7day1_index_new;M1region7day2_index_new;M1region7day3_index_new;];
% histogram(M1region7);

%% Monkey1
M1=[M1region1;M1region2;M1region3;M1region4;M1region5;M1region6;M1region7];
histogram(M1);
%% Monkey2 region1
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region1\20220426_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region1\20220427_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region1\20220428_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region1\20220429_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region1\20220430_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region1\20220501_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region1\20220502_index_new.mat');
M2region1=[M2region1day1_index_new;M2region1day2_index_new;M2region1day3_index_new;M2region1day4_index_new;M2region1day5_index_new;M2region1day6_index_new;M2region1day7_index_new];
% histogram(M2region1);

%% Monkey2 region2

load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region2\20220503_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region2\20220504_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region2\20220505_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region2\20220506_index_new.mat');
M2region2=[M2region2day1_index_new;M2region2day2_index_new;M2region2day3_index_new;M2region2day4_index_new;];
% histogram(M2region2);
%% Monkey2 region3
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region3\20220507_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region3\20220508_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region3\20220509_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region3\20220510_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region3\20220511_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region3\20220512_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region3\20220513_index_new.mat');
M2region3=[M2region3day1_index_new;M2region3day2_index_new;M2region3day3_index_new;M2region3day4_index_new;M2region3day5_index_new;M2region3day6_index_new;M2region3day7_index_new];
% histogram(M2region3);
%% Monkey2 region4
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region4\20220517_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region4\20220518_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region4\20220519_index_new.mat');
M2region4=[M2region4day1_index_new;M2region4day2_index_new;M2region4day3_index_new;];
% histogram(M2region4);
%% Monkey2 region5
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region5\20220524_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region5\20220526_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region5\20220527_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region5\20220528_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region5\20220529_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region5\20220530_index_new.mat');
M2region5=[M2region5day1_index_new;M2region5day2_index_new;M2region5day3_index_new;M2region5day4_index_new;M2region5day5_index_new;M2region5day6_index_new;];
% histogram(M2region5);

%% Monkey2 region6
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region6\20220610_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region6\20220611_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region6\20220612_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region6\20220613_index_new.mat');

M2region6=[M2region6day1_index_new;M2region6day2_index_new;M2region6day3_index_new;M2region6day4_index_new;];
% histogram(M2region6);

%% Monkey2 region7
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region7\20220618_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region7\20220619_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region7\20220620_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region7\20220621_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region7\20220622_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region7\20220623_index_new.mat');
M2region7=[M2region7day1_index_new;M2region7day2_index_new;M2region7day3_index_new;M2region7day4_index_new;M2region7day5_index_new;M2region7day6_index_new;];
% histogram(M2region7);
%% Monkey2 region8
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region8\20220624_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region8\20220627_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region8\20220628_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region8\20220629_index_new.mat');
load('L:\毕业论文\20220307预答辩\latency_time_duration_distribution\latency_time_duration\method_for_time_earlier_than_aligned_to_targetoff\for_only_cells_encoding_the_currenttrialoutcome\M2region8\20220630_index_new.mat');
M2region8=[M2region8day1_index_new;M2region8day2_index_new;M2region8day3_index_new;M2region8day4_index_new;M2region8day5_index_new;];
% histogram(M2region8);
M2=[M2region1;M2region2;M2region3;M2region4;M2region5;M2region6;M2region7;M2region8];

M=[M1;M2];
histogram(M);




